
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file Services.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using AppointmentSystem.Entities.Validation;
#endregion

namespace AppointmentSystem.Entities
{
	///<summary>
	/// Procedures, Services...	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class ServicesBase : EntityBase, IServices, IEntityId<ServicesKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private ServicesEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private ServicesEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private ServicesEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Services> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event ServicesEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event ServicesEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="ServicesBase"/> instance.
		///</summary>
		public ServicesBase()
		{
			this.entityData = new ServicesEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="ServicesBase"/> instance.
		///</summary>
		///<param name="_title"></param>
		///<param name="_shortTitle"></param>
		///<param name="_note"></param>
		///<param name="_priorityIndex"></param>
		///<param name="_isDisabled"></param>
		///<param name="_createUser"></param>
		///<param name="_createDate"></param>
		///<param name="_updateUser"></param>
		///<param name="_updateDate"></param>
		public ServicesBase(System.String _title, System.String _shortTitle, System.String _note, 
			System.Int32 _priorityIndex, System.Boolean _isDisabled, System.String _createUser, System.DateTime _createDate, 
			System.String _updateUser, System.DateTime _updateDate)
		{
			this.entityData = new ServicesEntityData();
			this.backupData = null;

			this.Title = _title;
			this.ShortTitle = _shortTitle;
			this.Note = _note;
			this.PriorityIndex = _priorityIndex;
			this.IsDisabled = _isDisabled;
			this.CreateUser = _createUser;
			this.CreateDate = _createDate;
			this.UpdateUser = _updateUser;
			this.UpdateDate = _updateDate;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Services"/> instance.
		///</summary>
		///<param name="_title"></param>
		///<param name="_shortTitle"></param>
		///<param name="_note"></param>
		///<param name="_priorityIndex"></param>
		///<param name="_isDisabled"></param>
		///<param name="_createUser"></param>
		///<param name="_createDate"></param>
		///<param name="_updateUser"></param>
		///<param name="_updateDate"></param>
		public static Services CreateServices(System.String _title, System.String _shortTitle, System.String _note, 
			System.Int32 _priorityIndex, System.Boolean _isDisabled, System.String _createUser, System.DateTime _createDate, 
			System.String _updateUser, System.DateTime _updateDate)
		{
			Services newServices = new Services();
			newServices.Title = _title;
			newServices.ShortTitle = _shortTitle;
			newServices.Note = _note;
			newServices.PriorityIndex = _priorityIndex;
			newServices.IsDisabled = _isDisabled;
			newServices.CreateUser = _createUser;
			newServices.CreateDate = _createDate;
			newServices.UpdateUser = _updateUser;
			newServices.UpdateDate = _updateDate;
			return newServices;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
					
				OnColumnChanging(ServicesColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ServicesColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Title property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 100)]
		public virtual System.String Title
		{
			get
			{
				return this.entityData.Title; 
			}
			
			set
			{
				if (this.entityData.Title == value)
					return;
					
				OnColumnChanging(ServicesColumn.Title, this.entityData.Title);
				this.entityData.Title = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ServicesColumn.Title, this.entityData.Title);
				OnPropertyChanged("Title");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ShortTitle property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String ShortTitle
		{
			get
			{
				return this.entityData.ShortTitle; 
			}
			
			set
			{
				if (this.entityData.ShortTitle == value)
					return;
					
				OnColumnChanging(ServicesColumn.ShortTitle, this.entityData.ShortTitle);
				this.entityData.ShortTitle = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ServicesColumn.ShortTitle, this.entityData.ShortTitle);
				OnPropertyChanged("ShortTitle");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Note property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 500)]
		public virtual System.String Note
		{
			get
			{
				return this.entityData.Note; 
			}
			
			set
			{
				if (this.entityData.Note == value)
					return;
					
				OnColumnChanging(ServicesColumn.Note, this.entityData.Note);
				this.entityData.Note = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ServicesColumn.Note, this.entityData.Note);
				OnPropertyChanged("Note");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the PriorityIndex property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 PriorityIndex
		{
			get
			{
				return this.entityData.PriorityIndex; 
			}
			
			set
			{
				if (this.entityData.PriorityIndex == value)
					return;
					
				OnColumnChanging(ServicesColumn.PriorityIndex, this.entityData.PriorityIndex);
				this.entityData.PriorityIndex = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ServicesColumn.PriorityIndex, this.entityData.PriorityIndex);
				OnPropertyChanged("PriorityIndex");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IsDisabled property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Boolean IsDisabled
		{
			get
			{
				return this.entityData.IsDisabled; 
			}
			
			set
			{
				if (this.entityData.IsDisabled == value)
					return;
					
				OnColumnChanging(ServicesColumn.IsDisabled, this.entityData.IsDisabled);
				this.entityData.IsDisabled = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ServicesColumn.IsDisabled, this.entityData.IsDisabled);
				OnPropertyChanged("IsDisabled");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CreateUser property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public override System.String CreateUser
		{
			get
			{
				return this.entityData.CreateUser; 
			}
			
			set
			{
				if (this.entityData.CreateUser == value)
					return;
					
				OnColumnChanging(ServicesColumn.CreateUser, this.entityData.CreateUser);
				this.entityData.CreateUser = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ServicesColumn.CreateUser, this.entityData.CreateUser);
				OnPropertyChanged("CreateUser");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CreateDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public override System.DateTime CreateDate
		{
			get
			{
				return this.entityData.CreateDate; 
			}
			
			set
			{
				if (this.entityData.CreateDate == value)
					return;
					
				OnColumnChanging(ServicesColumn.CreateDate, this.entityData.CreateDate);
				this.entityData.CreateDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ServicesColumn.CreateDate, this.entityData.CreateDate);
				OnPropertyChanged("CreateDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the UpdateUser property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public override System.String UpdateUser
		{
			get
			{
				return this.entityData.UpdateUser; 
			}
			
			set
			{
				if (this.entityData.UpdateUser == value)
					return;
					
				OnColumnChanging(ServicesColumn.UpdateUser, this.entityData.UpdateUser);
				this.entityData.UpdateUser = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ServicesColumn.UpdateUser, this.entityData.UpdateUser);
				OnPropertyChanged("UpdateUser");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the UpdateDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public override System.DateTime UpdateDate
		{
			get
			{
				return this.entityData.UpdateDate; 
			}
			
			set
			{
				if (this.entityData.UpdateDate == value)
					return;
					
				OnColumnChanging(ServicesColumn.UpdateDate, this.entityData.UpdateDate);
				this.entityData.UpdateDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ServicesColumn.UpdateDate, this.entityData.UpdateDate);
				OnPropertyChanged("UpdateDate");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of DoctorService objects
		///	which are related to this object through the relation FK_DoctorService_Services
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<DoctorService> DoctorServiceCollection
		{
			get { return entityData.DoctorServiceCollection; }
			set { entityData.DoctorServiceCollection = value; }	
		}
	
		/// <summary>
		///	Holds a collection of Appointment objects
		///	which are related to this object through the relation FK_Appointment_Procedure
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Appointment> AppointmentCollection
		{
			get { return entityData.AppointmentCollection; }
			set { entityData.AppointmentCollection = value; }	
		}
	
		/// <summary>
		///	Holds a collection of Room objects
		///	which are related to this object through the relation FK_Room_Procedure
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Room> RoomCollection
		{
			get { return entityData.RoomCollection; }
			set { entityData.RoomCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Title", "Title", 100));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("ShortTitle", "Short Title", 20));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Note", "Note", 500));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("CreateUser", "Create User", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("UpdateUser", "Update User", 50));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "Services"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"Id", "Title", "ShortTitle", "Note", "PriorityIndex", "IsDisabled", "CreateUser", "CreateDate", "UpdateUser", "UpdateDate"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as ServicesEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Services) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Services>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Services);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Services Entity 
		///</summary>
		protected virtual Services Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			Services copy = new Services();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Id = this.Id;
				copy.Title = this.Title;
				copy.ShortTitle = this.ShortTitle;
				copy.Note = this.Note;
				copy.PriorityIndex = this.PriorityIndex;
				copy.IsDisabled = this.IsDisabled;
				copy.CreateUser = this.CreateUser;
				copy.CreateDate = this.CreateDate;
				copy.UpdateUser = this.UpdateUser;
				copy.UpdateDate = this.UpdateDate;
			
		
			//deep copy nested objects
			copy.DoctorServiceCollection = (TList<DoctorService>) MakeCopyOf(this.DoctorServiceCollection, existingCopies); 
			copy.AppointmentCollection = (TList<Appointment>) MakeCopyOf(this.AppointmentCollection, existingCopies); 
			copy.RoomCollection = (TList<Room>) MakeCopyOf(this.RoomCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed Services Entity 
		///</summary>
		public virtual Services Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed Services Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Services DeepCopy()
		{
			return EntityHelper.Clone<Services>(this as Services);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as ServicesEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new ServicesEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as ServicesEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(ServicesColumn column)
		{
			switch(column)
			{
					case ServicesColumn.Id:
					return entityData.Id != _originalData.Id;
					case ServicesColumn.Title:
					return entityData.Title != _originalData.Title;
					case ServicesColumn.ShortTitle:
					return entityData.ShortTitle != _originalData.ShortTitle;
					case ServicesColumn.Note:
					return entityData.Note != _originalData.Note;
					case ServicesColumn.PriorityIndex:
					return entityData.PriorityIndex != _originalData.PriorityIndex;
					case ServicesColumn.IsDisabled:
					return entityData.IsDisabled != _originalData.IsDisabled;
					case ServicesColumn.CreateUser:
					return entityData.CreateUser != _originalData.CreateUser;
					case ServicesColumn.CreateDate:
					return entityData.CreateDate != _originalData.CreateDate;
					case ServicesColumn.UpdateUser:
					return entityData.UpdateUser != _originalData.UpdateUser;
					case ServicesColumn.UpdateDate:
					return entityData.UpdateDate != _originalData.UpdateDate;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< ServicesColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Id != _originalData.Id;
			result = result || entityData.Title != _originalData.Title;
			result = result || entityData.ShortTitle != _originalData.ShortTitle;
			result = result || entityData.Note != _originalData.Note;
			result = result || entityData.PriorityIndex != _originalData.PriorityIndex;
			result = result || entityData.IsDisabled != _originalData.IsDisabled;
			result = result || entityData.CreateUser != _originalData.CreateUser;
			result = result || entityData.CreateDate != _originalData.CreateDate;
			result = result || entityData.UpdateUser != _originalData.UpdateUser;
			result = result || entityData.UpdateDate != _originalData.UpdateDate;
			return result;
		}	
		
		///<summary>
		///  Returns a Services Entity with the original data.
		///</summary>
		public Services GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateServices(
				_originalData.Title,
				_originalData.ShortTitle,
				_originalData.Note,
				_originalData.PriorityIndex,
				_originalData.IsDisabled,
				_originalData.CreateUser,
				_originalData.CreateDate,
				_originalData.UpdateUser,
				_originalData.UpdateDate
				);
				
			return (Services)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="ServicesBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is ServicesBase)
				return ValueEquals(this, (ServicesBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="ServicesBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Id.GetHashCode() ^ 
					((this.Title == null) ? string.Empty : this.Title.ToString()).GetHashCode() ^ 
					((this.ShortTitle == null) ? string.Empty : this.ShortTitle.ToString()).GetHashCode() ^ 
					((this.Note == null) ? string.Empty : this.Note.ToString()).GetHashCode() ^ 
					this.PriorityIndex.GetHashCode() ^ 
					this.IsDisabled.GetHashCode() ^ 
					((this.CreateUser == null) ? string.Empty : this.CreateUser.ToString()).GetHashCode() ^ 
					this.CreateDate.GetHashCode() ^ 
					((this.UpdateUser == null) ? string.Empty : this.UpdateUser.ToString()).GetHashCode() ^ 
					this.UpdateDate.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="ServicesBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(ServicesBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="ServicesBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="ServicesBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="ServicesBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(ServicesBase Object1, ServicesBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Id != Object2.Id)
				equal = false;
			if ( Object1.Title != null && Object2.Title != null )
			{
				if (Object1.Title != Object2.Title)
					equal = false;
			}
			else if (Object1.Title == null ^ Object2.Title == null )
			{
				equal = false;
			}
			if ( Object1.ShortTitle != null && Object2.ShortTitle != null )
			{
				if (Object1.ShortTitle != Object2.ShortTitle)
					equal = false;
			}
			else if (Object1.ShortTitle == null ^ Object2.ShortTitle == null )
			{
				equal = false;
			}
			if ( Object1.Note != null && Object2.Note != null )
			{
				if (Object1.Note != Object2.Note)
					equal = false;
			}
			else if (Object1.Note == null ^ Object2.Note == null )
			{
				equal = false;
			}
			if (Object1.PriorityIndex != Object2.PriorityIndex)
				equal = false;
			if (Object1.IsDisabled != Object2.IsDisabled)
				equal = false;
			if ( Object1.CreateUser != null && Object2.CreateUser != null )
			{
				if (Object1.CreateUser != Object2.CreateUser)
					equal = false;
			}
			else if (Object1.CreateUser == null ^ Object2.CreateUser == null )
			{
				equal = false;
			}
			if (Object1.CreateDate != Object2.CreateDate)
				equal = false;
			if ( Object1.UpdateUser != null && Object2.UpdateUser != null )
			{
				if (Object1.UpdateUser != Object2.UpdateUser)
					equal = false;
			}
			else if (Object1.UpdateUser == null ^ Object2.UpdateUser == null )
			{
				equal = false;
			}
			if (Object1.UpdateDate != Object2.UpdateDate)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((ServicesBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static ServicesComparer GetComparer()
        {
            return new ServicesComparer();
        }
        */

        // Comparer delegates back to Services
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Services rhs, ServicesColumn which)
        {
            switch (which)
            {
            	
            	
            	case ServicesColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            	
            	
            	case ServicesColumn.Title:
            		return this.Title.CompareTo(rhs.Title);
            		
            		                 
            	
            	
            	case ServicesColumn.ShortTitle:
            		return this.ShortTitle.CompareTo(rhs.ShortTitle);
            		
            		                 
            	
            	
            	case ServicesColumn.Note:
            		return this.Note.CompareTo(rhs.Note);
            		
            		                 
            	
            	
            	case ServicesColumn.PriorityIndex:
            		return this.PriorityIndex.CompareTo(rhs.PriorityIndex);
            		
            		                 
            	
            	
            	case ServicesColumn.IsDisabled:
            		return this.IsDisabled.CompareTo(rhs.IsDisabled);
            		
            		                 
            	
            	
            	case ServicesColumn.CreateUser:
            		return this.CreateUser.CompareTo(rhs.CreateUser);
            		
            		                 
            	
            	
            	case ServicesColumn.CreateDate:
            		return this.CreateDate.CompareTo(rhs.CreateDate);
            		
            		                 
            	
            	
            	case ServicesColumn.UpdateUser:
            		return this.UpdateUser.CompareTo(rhs.UpdateUser);
            		
            		                 
            	
            	
            	case ServicesColumn.UpdateDate:
            		return this.UpdateDate.CompareTo(rhs.UpdateDate);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<ServicesKey> Members
		
		// member variable for the EntityId property
		private ServicesKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual ServicesKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new ServicesKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Services")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{11}{10}- Id: {0}{10}- Title: {1}{10}- ShortTitle: {2}{10}- Note: {3}{10}- PriorityIndex: {4}{10}- IsDisabled: {5}{10}- CreateUser: {6}{10}- CreateDate: {7}{10}- UpdateUser: {8}{10}- UpdateDate: {9}{10}{12}", 
				this.Id,
				(this.Title == null) ? string.Empty : this.Title.ToString(),
				(this.ShortTitle == null) ? string.Empty : this.ShortTitle.ToString(),
				(this.Note == null) ? string.Empty : this.Note.ToString(),
				this.PriorityIndex,
				this.IsDisabled,
				(this.CreateUser == null) ? string.Empty : this.CreateUser.ToString(),
				this.CreateDate,
				(this.UpdateUser == null) ? string.Empty : this.UpdateUser.ToString(),
				this.UpdateDate,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'Services' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class ServicesEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Services"</remarks>
		public System.Int32 Id;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// Title : 
		/// </summary>
		public System.String		  Title = null;
		
		/// <summary>
		/// ShortTitle : 
		/// </summary>
		public System.String		  ShortTitle = null;
		
		/// <summary>
		/// Note : 
		/// </summary>
		public System.String		  Note = null;
		
		/// <summary>
		/// PriorityIndex : 
		/// </summary>
		public System.Int32		  PriorityIndex = (int)1;
		
		/// <summary>
		/// IsDisabled : 
		/// </summary>
		public System.Boolean		  IsDisabled = false;
		
		/// <summary>
		/// CreateUser : 
		/// </summary>
		public System.String		  CreateUser = null;
		
		/// <summary>
		/// CreateDate : 
		/// </summary>
		public System.DateTime		  CreateDate = DateTime.Now;
		
		/// <summary>
		/// UpdateUser : 
		/// </summary>
		public System.String		  UpdateUser = null;
		
		/// <summary>
		/// UpdateDate : 
		/// </summary>
		public System.DateTime		  UpdateDate = DateTime.Now;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#region DoctorServiceCollection
		
		private TList<DoctorService> _doctorServiceServiceId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _doctorServiceServiceId
		/// </summary>
		
		public TList<DoctorService> DoctorServiceCollection
		{
			get
			{
				if (_doctorServiceServiceId == null)
				{
				_doctorServiceServiceId = new TList<DoctorService>();
				}
	
				return _doctorServiceServiceId;
			}
			set { _doctorServiceServiceId = value; }
		}
		
		#endregion

		#region AppointmentCollection
		
		private TList<Appointment> _appointmentServicesId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _appointmentServicesId
		/// </summary>
		
		public TList<Appointment> AppointmentCollection
		{
			get
			{
				if (_appointmentServicesId == null)
				{
				_appointmentServicesId = new TList<Appointment>();
				}
	
				return _appointmentServicesId;
			}
			set { _appointmentServicesId = value; }
		}
		
		#endregion

		#region RoomCollection
		
		private TList<Room> _roomServicesId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _roomServicesId
		/// </summary>
		
		public TList<Room> RoomCollection
		{
			get
			{
				if (_roomServicesId == null)
				{
				_roomServicesId = new TList<Room>();
				}
	
				return _roomServicesId;
			}
			set { _roomServicesId = value; }
		}
		
		#endregion

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			ServicesEntityData _tmp = new ServicesEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.Title = this.Title;
			_tmp.ShortTitle = this.ShortTitle;
			_tmp.Note = this.Note;
			_tmp.PriorityIndex = this.PriorityIndex;
			_tmp.IsDisabled = this.IsDisabled;
			_tmp.CreateUser = this.CreateUser;
			_tmp.CreateDate = this.CreateDate;
			_tmp.UpdateUser = this.UpdateUser;
			_tmp.UpdateDate = this.UpdateDate;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._doctorServiceServiceId != null)
				_tmp.DoctorServiceCollection = (TList<DoctorService>) MakeCopyOf(this.DoctorServiceCollection); 
			if (this._appointmentServicesId != null)
				_tmp.AppointmentCollection = (TList<Appointment>) MakeCopyOf(this.AppointmentCollection); 
			if (this._roomServicesId != null)
				_tmp.RoomCollection = (TList<Room>) MakeCopyOf(this.RoomCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			ServicesEntityData _tmp = new ServicesEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.Title = this.Title;
			_tmp.ShortTitle = this.ShortTitle;
			_tmp.Note = this.Note;
			_tmp.PriorityIndex = this.PriorityIndex;
			_tmp.IsDisabled = this.IsDisabled;
			_tmp.CreateUser = this.CreateUser;
			_tmp.CreateDate = this.CreateDate;
			_tmp.UpdateUser = this.UpdateUser;
			_tmp.UpdateDate = this.UpdateDate;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.DoctorServiceCollection = (TList<DoctorService>) MakeCopyOf(this.DoctorServiceCollection, existingCopies); 
			_tmp.AppointmentCollection = (TList<Appointment>) MakeCopyOf(this.AppointmentCollection, existingCopies); 
			_tmp.RoomCollection = (TList<Room>) MakeCopyOf(this.RoomCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ServicesColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(ServicesColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ServicesColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(ServicesColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ServicesColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(ServicesColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				ServicesEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new ServicesEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ServicesColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(ServicesColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				ServicesEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new ServicesEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region ServicesEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Services"/> object.
	/// </remarks>
	public class ServicesEventArgs : System.EventArgs
	{
		private ServicesColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the ServicesEventArgs class.
		///</summary>
		public ServicesEventArgs(ServicesColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the ServicesEventArgs class.
		///</summary>
		public ServicesEventArgs(ServicesColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The ServicesColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="ServicesColumn" />
		public ServicesColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Services related events.
	///</summary>
	public delegate void ServicesEventHandler(object sender, ServicesEventArgs e);
	
	#region ServicesComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class ServicesComparer : System.Collections.Generic.IComparer<Services>
	{
		ServicesColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:ServicesComparer"/> class.
        /// </summary>
		public ServicesComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:ServicesComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public ServicesComparer(ServicesColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="Services"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="Services"/> to compare.</param>
        /// <param name="b">The second <c>Services</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Services a, Services b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Services entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Services a, Services b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public ServicesColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region ServicesKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Services"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class ServicesKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the ServicesKey class.
		/// </summary>
		public ServicesKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the ServicesKey class.
		/// </summary>
		public ServicesKey(ServicesBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the ServicesKey class.
		/// </summary>
		public ServicesKey(System.Int32 _id)
		{
			#region Init Properties

			this.Id = _id;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private ServicesBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public ServicesBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.Int32 _id;
		
		/// <summary>
		/// Gets or sets the Id property.
		/// </summary>
		public System.Int32 Id
		{
			get { return _id; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_id = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["Id"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",
								Id,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region ServicesColumn Enum
	
	/// <summary>
	/// Enumerate the Services columns.
	/// </summary>
	[Serializable]
	public enum ServicesColumn : int
	{
		/// <summary>
		/// Id : 
		/// </summary>
		[EnumTextValue("Id")]
		[ColumnEnum("Id", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		Id = 1,
		/// <summary>
		/// Title : 
		/// </summary>
		[EnumTextValue("Title")]
		[ColumnEnum("Title", typeof(System.String), System.Data.DbType.String, false, false, true, 100)]
		Title = 2,
		/// <summary>
		/// ShortTitle : 
		/// </summary>
		[EnumTextValue("ShortTitle")]
		[ColumnEnum("ShortTitle", typeof(System.String), System.Data.DbType.String, false, false, true, 20)]
		ShortTitle = 3,
		/// <summary>
		/// Note : 
		/// </summary>
		[EnumTextValue("Note")]
		[ColumnEnum("Note", typeof(System.String), System.Data.DbType.String, false, false, true, 500)]
		Note = 4,
		/// <summary>
		/// PriorityIndex : 
		/// </summary>
		[EnumTextValue("PriorityIndex")]
		[ColumnEnum("PriorityIndex", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		PriorityIndex = 5,
		/// <summary>
		/// IsDisabled : 
		/// </summary>
		[EnumTextValue("IsDisabled")]
		[ColumnEnum("IsDisabled", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, false)]
		IsDisabled = 6,
		/// <summary>
		/// CreateUser : 
		/// </summary>
		[EnumTextValue("CreateUser")]
		[ColumnEnum("CreateUser", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		CreateUser = 7,
		/// <summary>
		/// CreateDate : 
		/// </summary>
		[EnumTextValue("CreateDate")]
		[ColumnEnum("CreateDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		CreateDate = 8,
		/// <summary>
		/// UpdateUser : 
		/// </summary>
		[EnumTextValue("UpdateUser")]
		[ColumnEnum("UpdateUser", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		UpdateUser = 9,
		/// <summary>
		/// UpdateDate : 
		/// </summary>
		[EnumTextValue("UpdateDate")]
		[ColumnEnum("UpdateDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		UpdateDate = 10
	}//End enum

	#endregion ServicesColumn Enum

} // end namespace
