using System;
using System.ComponentModel;

namespace AppointmentSystem.Entities
{
	/// <summary>
	///		The data structure representation of the 'SmsReceiver' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface ISmsReceiver 
	{
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "SmsReceiver"</remarks>
		System.Int64 Id { get; set; }
				
		
		
		/// <summary>
		/// Mobile : 
		/// </summary>
		System.String  Mobile  { get; set; }
		
		/// <summary>
		/// FirstName : 
		/// </summary>
		System.String  FirstName  { get; set; }
		
		/// <summary>
		/// LastName : 
		/// </summary>
		System.String  LastName  { get; set; }
		
		/// <summary>
		/// UserType : Loại người dùng nhận tin: 1. Doctor, 2: Patient
		/// </summary>
		System.Byte  UserType  { get; set; }
		
		/// <summary>
		/// SmsId : 
		/// </summary>
		System.Int64  SmsId  { get; set; }
		
		/// <summary>
		/// IsSent : Sms này đã được gửi chưa
		/// </summary>
		System.Boolean  IsSent  { get; set; }
		
		/// <summary>
		/// SendingTimes : Số lần SMS này được gửi. Vì có thể gửi lại
		/// </summary>
		System.Int32  SendingTimes  { get; set; }
		
		/// <summary>
		/// Note : 
		/// </summary>
		System.String  Note  { get; set; }
		
		/// <summary>
		/// IsDisabled : 
		/// </summary>
		System.Boolean  IsDisabled  { get; set; }
		
		/// <summary>
		/// CreateUser : 
		/// </summary>
		System.String  CreateUser  { get; set; }
		
		/// <summary>
		/// CreateDate : 
		/// </summary>
		System.DateTime  CreateDate  { get; set; }
		
		/// <summary>
		/// UpdateUser : 
		/// </summary>
		System.String  UpdateUser  { get; set; }
		
		/// <summary>
		/// UpdateDate : 
		/// </summary>
		System.DateTime  UpdateDate  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


