
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file Sms.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using AppointmentSystem.Entities.Validation;
#endregion

namespace AppointmentSystem.Entities
{
	///<summary>
	/// An object representation of the 'Sms' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class SmsBase : EntityBase, ISms, IEntityId<SmsKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private SmsEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private SmsEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private SmsEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Sms> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event SmsEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event SmsEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="SmsBase"/> instance.
		///</summary>
		public SmsBase()
		{
			this.entityData = new SmsEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="SmsBase"/> instance.
		///</summary>
		///<param name="_message"></param>
		///<param name="_smsType">Loại SMS: 1. SMS từ appointment, 2. SMS khác [do admin tự tạo]</param>
		///<param name="_sendTime">Thời gian gửi tin nhắn</param>
		///<param name="_isSendNow">Có gửi ngay hay không. Nếu không sẽ được gửi bằng windows service</param>
		///<param name="_isSent">Sms này đã được gửi chưa</param>
		///<param name="_sendingTimes">Số lần SMS này được gửi. Vì có thể gửi lại</param>
		///<param name="_appointmentId">Id của appointment nếu đó là loại của appointment</param>
		///<param name="_note"></param>
		///<param name="_isDisabled"></param>
		///<param name="_createUser"></param>
		///<param name="_createDate"></param>
		///<param name="_updateUser"></param>
		///<param name="_updateDate"></param>
		public SmsBase(System.String _message, System.Byte _smsType, System.DateTime _sendTime, System.Boolean _isSendNow, 
			System.Boolean _isSent, System.Int32 _sendingTimes, System.String _appointmentId, System.String _note, System.Boolean _isDisabled, 
			System.String _createUser, System.DateTime _createDate, System.String _updateUser, System.DateTime _updateDate)
		{
			this.entityData = new SmsEntityData();
			this.backupData = null;

			this.Message = _message;
			this.SmsType = _smsType;
			this.SendTime = _sendTime;
			this.IsSendNow = _isSendNow;
			this.IsSent = _isSent;
			this.SendingTimes = _sendingTimes;
			this.AppointmentId = _appointmentId;
			this.Note = _note;
			this.IsDisabled = _isDisabled;
			this.CreateUser = _createUser;
			this.CreateDate = _createDate;
			this.UpdateUser = _updateUser;
			this.UpdateDate = _updateDate;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Sms"/> instance.
		///</summary>
		///<param name="_message"></param>
		///<param name="_smsType">Loại SMS: 1. SMS từ appointment, 2. SMS khác [do admin tự tạo]</param>
		///<param name="_sendTime">Thời gian gửi tin nhắn</param>
		///<param name="_isSendNow">Có gửi ngay hay không. Nếu không sẽ được gửi bằng windows service</param>
		///<param name="_isSent">Sms này đã được gửi chưa</param>
		///<param name="_sendingTimes">Số lần SMS này được gửi. Vì có thể gửi lại</param>
		///<param name="_appointmentId">Id của appointment nếu đó là loại của appointment</param>
		///<param name="_note"></param>
		///<param name="_isDisabled"></param>
		///<param name="_createUser"></param>
		///<param name="_createDate"></param>
		///<param name="_updateUser"></param>
		///<param name="_updateDate"></param>
		public static Sms CreateSms(System.String _message, System.Byte _smsType, System.DateTime _sendTime, System.Boolean _isSendNow, 
			System.Boolean _isSent, System.Int32 _sendingTimes, System.String _appointmentId, System.String _note, System.Boolean _isDisabled, 
			System.String _createUser, System.DateTime _createDate, System.String _updateUser, System.DateTime _updateDate)
		{
			Sms newSms = new Sms();
			newSms.Message = _message;
			newSms.SmsType = _smsType;
			newSms.SendTime = _sendTime;
			newSms.IsSendNow = _isSendNow;
			newSms.IsSent = _isSent;
			newSms.SendingTimes = _sendingTimes;
			newSms.AppointmentId = _appointmentId;
			newSms.Note = _note;
			newSms.IsDisabled = _isDisabled;
			newSms.CreateUser = _createUser;
			newSms.CreateDate = _createDate;
			newSms.UpdateUser = _updateUser;
			newSms.UpdateDate = _updateDate;
			return newSms;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int64 Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
					
				OnColumnChanging(SmsColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SmsColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Message property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 256)]
		public virtual System.String Message
		{
			get
			{
				return this.entityData.Message; 
			}
			
			set
			{
				if (this.entityData.Message == value)
					return;
					
				OnColumnChanging(SmsColumn.Message, this.entityData.Message);
				this.entityData.Message = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SmsColumn.Message, this.entityData.Message);
				OnPropertyChanged("Message");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SmsType property. 
		///		Loại SMS: 1. SMS từ appointment, 2. SMS khác [do admin tự tạo]
		/// </summary>
		/// <value>This type is tinyint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@"Loại SMS: 1. SMS từ appointment, 2. SMS khác [do admin tự tạo]"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Byte SmsType
		{
			get
			{
				return this.entityData.SmsType; 
			}
			
			set
			{
				if (this.entityData.SmsType == value)
					return;
					
				OnColumnChanging(SmsColumn.SmsType, this.entityData.SmsType);
				this.entityData.SmsType = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SmsColumn.SmsType, this.entityData.SmsType);
				OnPropertyChanged("SmsType");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SendTime property. 
		///		Thời gian gửi tin nhắn
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@"Thời gian gửi tin nhắn"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime SendTime
		{
			get
			{
				return this.entityData.SendTime; 
			}
			
			set
			{
				if (this.entityData.SendTime == value)
					return;
					
				OnColumnChanging(SmsColumn.SendTime, this.entityData.SendTime);
				this.entityData.SendTime = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SmsColumn.SendTime, this.entityData.SendTime);
				OnPropertyChanged("SendTime");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IsSendNow property. 
		///		Có gửi ngay hay không. Nếu không sẽ được gửi bằng windows service
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@"Có gửi ngay hay không. Nếu không sẽ được gửi bằng windows service"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Boolean IsSendNow
		{
			get
			{
				return this.entityData.IsSendNow; 
			}
			
			set
			{
				if (this.entityData.IsSendNow == value)
					return;
					
				OnColumnChanging(SmsColumn.IsSendNow, this.entityData.IsSendNow);
				this.entityData.IsSendNow = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SmsColumn.IsSendNow, this.entityData.IsSendNow);
				OnPropertyChanged("IsSendNow");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IsSent property. 
		///		Sms này đã được gửi chưa
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@"Sms này đã được gửi chưa"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Boolean IsSent
		{
			get
			{
				return this.entityData.IsSent; 
			}
			
			set
			{
				if (this.entityData.IsSent == value)
					return;
					
				OnColumnChanging(SmsColumn.IsSent, this.entityData.IsSent);
				this.entityData.IsSent = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SmsColumn.IsSent, this.entityData.IsSent);
				OnPropertyChanged("IsSent");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SendingTimes property. 
		///		Số lần SMS này được gửi. Vì có thể gửi lại
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@"Số lần SMS này được gửi. Vì có thể gửi lại"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 SendingTimes
		{
			get
			{
				return this.entityData.SendingTimes; 
			}
			
			set
			{
				if (this.entityData.SendingTimes == value)
					return;
					
				OnColumnChanging(SmsColumn.SendingTimes, this.entityData.SendingTimes);
				this.entityData.SendingTimes = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SmsColumn.SendingTimes, this.entityData.SendingTimes);
				OnPropertyChanged("SendingTimes");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the AppointmentId property. 
		///		Id của appointment nếu đó là loại của appointment
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@"Id của appointment nếu đó là loại của appointment"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String AppointmentId
		{
			get
			{
				return this.entityData.AppointmentId; 
			}
			
			set
			{
				if (this.entityData.AppointmentId == value)
					return;
					
				OnColumnChanging(SmsColumn.AppointmentId, this.entityData.AppointmentId);
				this.entityData.AppointmentId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SmsColumn.AppointmentId, this.entityData.AppointmentId);
				OnPropertyChanged("AppointmentId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Note property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 1024)]
		public virtual System.String Note
		{
			get
			{
				return this.entityData.Note; 
			}
			
			set
			{
				if (this.entityData.Note == value)
					return;
					
				OnColumnChanging(SmsColumn.Note, this.entityData.Note);
				this.entityData.Note = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SmsColumn.Note, this.entityData.Note);
				OnPropertyChanged("Note");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IsDisabled property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Boolean IsDisabled
		{
			get
			{
				return this.entityData.IsDisabled; 
			}
			
			set
			{
				if (this.entityData.IsDisabled == value)
					return;
					
				OnColumnChanging(SmsColumn.IsDisabled, this.entityData.IsDisabled);
				this.entityData.IsDisabled = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SmsColumn.IsDisabled, this.entityData.IsDisabled);
				OnPropertyChanged("IsDisabled");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CreateUser property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 200)]
		public virtual System.String CreateUser
		{
			get
			{
				return this.entityData.CreateUser; 
			}
			
			set
			{
				if (this.entityData.CreateUser == value)
					return;
					
				OnColumnChanging(SmsColumn.CreateUser, this.entityData.CreateUser);
				this.entityData.CreateUser = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SmsColumn.CreateUser, this.entityData.CreateUser);
				OnPropertyChanged("CreateUser");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CreateDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime CreateDate
		{
			get
			{
				return this.entityData.CreateDate; 
			}
			
			set
			{
				if (this.entityData.CreateDate == value)
					return;
					
				OnColumnChanging(SmsColumn.CreateDate, this.entityData.CreateDate);
				this.entityData.CreateDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SmsColumn.CreateDate, this.entityData.CreateDate);
				OnPropertyChanged("CreateDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the UpdateUser property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 200)]
		public virtual System.String UpdateUser
		{
			get
			{
				return this.entityData.UpdateUser; 
			}
			
			set
			{
				if (this.entityData.UpdateUser == value)
					return;
					
				OnColumnChanging(SmsColumn.UpdateUser, this.entityData.UpdateUser);
				this.entityData.UpdateUser = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SmsColumn.UpdateUser, this.entityData.UpdateUser);
				OnPropertyChanged("UpdateUser");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the UpdateDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime UpdateDate
		{
			get
			{
				return this.entityData.UpdateDate; 
			}
			
			set
			{
				if (this.entityData.UpdateDate == value)
					return;
					
				OnColumnChanging(SmsColumn.UpdateDate, this.entityData.UpdateDate);
				this.entityData.UpdateDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SmsColumn.UpdateDate, this.entityData.UpdateDate);
				OnPropertyChanged("UpdateDate");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Appointment"/>.
		/// </summary>
		/// <value>The source Appointment for AppointmentId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Appointment AppointmentIdSource
      	{
            get { return entityData.AppointmentIdSource; }
            set { entityData.AppointmentIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of SmsLog objects
		///	which are related to this object through the relation FK_SmsLog_Sms
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<SmsLog> SmsLogCollection
		{
			get { return entityData.SmsLogCollection; }
			set { entityData.SmsLogCollection = value; }	
		}
	
		/// <summary>
		///	Holds a collection of SmsReceiver objects
		///	which are related to this object through the relation FK_SmsReceiver_Sms
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<SmsReceiver> SmsReceiverCollection
		{
			get { return entityData.SmsReceiverCollection; }
			set { entityData.SmsReceiverCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Message", "Message", 256));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("AppointmentId", "Appointment Id", 20));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Note", "Note", 1024));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("CreateUser", "Create User", 200));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("UpdateUser", "Update User", 200));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "Sms"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"Id", "Message", "SmsType", "SendTime", "IsSendNow", "IsSent", "SendingTimes", "AppointmentId", "Note", "IsDisabled", "CreateUser", "CreateDate", "UpdateUser", "UpdateDate"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as SmsEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Sms) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Sms>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Sms);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Sms Entity 
		///</summary>
		protected virtual Sms Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			Sms copy = new Sms();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Id = this.Id;
				copy.Message = this.Message;
				copy.SmsType = this.SmsType;
				copy.SendTime = this.SendTime;
				copy.IsSendNow = this.IsSendNow;
				copy.IsSent = this.IsSent;
				copy.SendingTimes = this.SendingTimes;
				copy.AppointmentId = this.AppointmentId;
				copy.Note = this.Note;
				copy.IsDisabled = this.IsDisabled;
				copy.CreateUser = this.CreateUser;
				copy.CreateDate = this.CreateDate;
				copy.UpdateUser = this.UpdateUser;
				copy.UpdateDate = this.UpdateDate;
			
			if (this.AppointmentIdSource != null && existingCopies.Contains(this.AppointmentIdSource))
				copy.AppointmentIdSource = existingCopies[this.AppointmentIdSource] as Appointment;
			else
				copy.AppointmentIdSource = MakeCopyOf(this.AppointmentIdSource, existingCopies) as Appointment;
		
			//deep copy nested objects
			copy.SmsLogCollection = (TList<SmsLog>) MakeCopyOf(this.SmsLogCollection, existingCopies); 
			copy.SmsReceiverCollection = (TList<SmsReceiver>) MakeCopyOf(this.SmsReceiverCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed Sms Entity 
		///</summary>
		public virtual Sms Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed Sms Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Sms DeepCopy()
		{
			return EntityHelper.Clone<Sms>(this as Sms);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as SmsEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new SmsEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as SmsEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(SmsColumn column)
		{
			switch(column)
			{
					case SmsColumn.Id:
					return entityData.Id != _originalData.Id;
					case SmsColumn.Message:
					return entityData.Message != _originalData.Message;
					case SmsColumn.SmsType:
					return entityData.SmsType != _originalData.SmsType;
					case SmsColumn.SendTime:
					return entityData.SendTime != _originalData.SendTime;
					case SmsColumn.IsSendNow:
					return entityData.IsSendNow != _originalData.IsSendNow;
					case SmsColumn.IsSent:
					return entityData.IsSent != _originalData.IsSent;
					case SmsColumn.SendingTimes:
					return entityData.SendingTimes != _originalData.SendingTimes;
					case SmsColumn.AppointmentId:
					return entityData.AppointmentId != _originalData.AppointmentId;
					case SmsColumn.Note:
					return entityData.Note != _originalData.Note;
					case SmsColumn.IsDisabled:
					return entityData.IsDisabled != _originalData.IsDisabled;
					case SmsColumn.CreateUser:
					return entityData.CreateUser != _originalData.CreateUser;
					case SmsColumn.CreateDate:
					return entityData.CreateDate != _originalData.CreateDate;
					case SmsColumn.UpdateUser:
					return entityData.UpdateUser != _originalData.UpdateUser;
					case SmsColumn.UpdateDate:
					return entityData.UpdateDate != _originalData.UpdateDate;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< SmsColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Id != _originalData.Id;
			result = result || entityData.Message != _originalData.Message;
			result = result || entityData.SmsType != _originalData.SmsType;
			result = result || entityData.SendTime != _originalData.SendTime;
			result = result || entityData.IsSendNow != _originalData.IsSendNow;
			result = result || entityData.IsSent != _originalData.IsSent;
			result = result || entityData.SendingTimes != _originalData.SendingTimes;
			result = result || entityData.AppointmentId != _originalData.AppointmentId;
			result = result || entityData.Note != _originalData.Note;
			result = result || entityData.IsDisabled != _originalData.IsDisabled;
			result = result || entityData.CreateUser != _originalData.CreateUser;
			result = result || entityData.CreateDate != _originalData.CreateDate;
			result = result || entityData.UpdateUser != _originalData.UpdateUser;
			result = result || entityData.UpdateDate != _originalData.UpdateDate;
			return result;
		}	
		
		///<summary>
		///  Returns a Sms Entity with the original data.
		///</summary>
		public Sms GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateSms(
				_originalData.Message,
				_originalData.SmsType,
				_originalData.SendTime,
				_originalData.IsSendNow,
				_originalData.IsSent,
				_originalData.SendingTimes,
				_originalData.AppointmentId,
				_originalData.Note,
				_originalData.IsDisabled,
				_originalData.CreateUser,
				_originalData.CreateDate,
				_originalData.UpdateUser,
				_originalData.UpdateDate
				);
				
			return (Sms)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="SmsBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is SmsBase)
				return ValueEquals(this, (SmsBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="SmsBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Id.GetHashCode() ^ 
					((this.Message == null) ? string.Empty : this.Message.ToString()).GetHashCode() ^ 
					this.SmsType.GetHashCode() ^ 
					this.SendTime.GetHashCode() ^ 
					this.IsSendNow.GetHashCode() ^ 
					this.IsSent.GetHashCode() ^ 
					this.SendingTimes.GetHashCode() ^ 
					((this.AppointmentId == null) ? string.Empty : this.AppointmentId.ToString()).GetHashCode() ^ 
					((this.Note == null) ? string.Empty : this.Note.ToString()).GetHashCode() ^ 
					this.IsDisabled.GetHashCode() ^ 
					((this.CreateUser == null) ? string.Empty : this.CreateUser.ToString()).GetHashCode() ^ 
					this.CreateDate.GetHashCode() ^ 
					((this.UpdateUser == null) ? string.Empty : this.UpdateUser.ToString()).GetHashCode() ^ 
					this.UpdateDate.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="SmsBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(SmsBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="SmsBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="SmsBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="SmsBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(SmsBase Object1, SmsBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Id != Object2.Id)
				equal = false;
			if ( Object1.Message != null && Object2.Message != null )
			{
				if (Object1.Message != Object2.Message)
					equal = false;
			}
			else if (Object1.Message == null ^ Object2.Message == null )
			{
				equal = false;
			}
			if (Object1.SmsType != Object2.SmsType)
				equal = false;
			if (Object1.SendTime != Object2.SendTime)
				equal = false;
			if (Object1.IsSendNow != Object2.IsSendNow)
				equal = false;
			if (Object1.IsSent != Object2.IsSent)
				equal = false;
			if (Object1.SendingTimes != Object2.SendingTimes)
				equal = false;
			if ( Object1.AppointmentId != null && Object2.AppointmentId != null )
			{
				if (Object1.AppointmentId != Object2.AppointmentId)
					equal = false;
			}
			else if (Object1.AppointmentId == null ^ Object2.AppointmentId == null )
			{
				equal = false;
			}
			if ( Object1.Note != null && Object2.Note != null )
			{
				if (Object1.Note != Object2.Note)
					equal = false;
			}
			else if (Object1.Note == null ^ Object2.Note == null )
			{
				equal = false;
			}
			if (Object1.IsDisabled != Object2.IsDisabled)
				equal = false;
			if ( Object1.CreateUser != null && Object2.CreateUser != null )
			{
				if (Object1.CreateUser != Object2.CreateUser)
					equal = false;
			}
			else if (Object1.CreateUser == null ^ Object2.CreateUser == null )
			{
				equal = false;
			}
			if (Object1.CreateDate != Object2.CreateDate)
				equal = false;
			if ( Object1.UpdateUser != null && Object2.UpdateUser != null )
			{
				if (Object1.UpdateUser != Object2.UpdateUser)
					equal = false;
			}
			else if (Object1.UpdateUser == null ^ Object2.UpdateUser == null )
			{
				equal = false;
			}
			if (Object1.UpdateDate != Object2.UpdateDate)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((SmsBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static SmsComparer GetComparer()
        {
            return new SmsComparer();
        }
        */

        // Comparer delegates back to Sms
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Sms rhs, SmsColumn which)
        {
            switch (which)
            {
            	
            	
            	case SmsColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            	
            	
            	case SmsColumn.Message:
            		return this.Message.CompareTo(rhs.Message);
            		
            		                 
            	
            	
            	case SmsColumn.SmsType:
            		return this.SmsType.CompareTo(rhs.SmsType);
            		
            		                 
            	
            	
            	case SmsColumn.SendTime:
            		return this.SendTime.CompareTo(rhs.SendTime);
            		
            		                 
            	
            	
            	case SmsColumn.IsSendNow:
            		return this.IsSendNow.CompareTo(rhs.IsSendNow);
            		
            		                 
            	
            	
            	case SmsColumn.IsSent:
            		return this.IsSent.CompareTo(rhs.IsSent);
            		
            		                 
            	
            	
            	case SmsColumn.SendingTimes:
            		return this.SendingTimes.CompareTo(rhs.SendingTimes);
            		
            		                 
            	
            	
            	case SmsColumn.AppointmentId:
            		return this.AppointmentId.CompareTo(rhs.AppointmentId);
            		
            		                 
            	
            	
            	case SmsColumn.Note:
            		return this.Note.CompareTo(rhs.Note);
            		
            		                 
            	
            	
            	case SmsColumn.IsDisabled:
            		return this.IsDisabled.CompareTo(rhs.IsDisabled);
            		
            		                 
            	
            	
            	case SmsColumn.CreateUser:
            		return this.CreateUser.CompareTo(rhs.CreateUser);
            		
            		                 
            	
            	
            	case SmsColumn.CreateDate:
            		return this.CreateDate.CompareTo(rhs.CreateDate);
            		
            		                 
            	
            	
            	case SmsColumn.UpdateUser:
            		return this.UpdateUser.CompareTo(rhs.UpdateUser);
            		
            		                 
            	
            	
            	case SmsColumn.UpdateDate:
            		return this.UpdateDate.CompareTo(rhs.UpdateDate);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<SmsKey> Members
		
		// member variable for the EntityId property
		private SmsKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual SmsKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new SmsKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Sms")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{15}{14}- Id: {0}{14}- Message: {1}{14}- SmsType: {2}{14}- SendTime: {3}{14}- IsSendNow: {4}{14}- IsSent: {5}{14}- SendingTimes: {6}{14}- AppointmentId: {7}{14}- Note: {8}{14}- IsDisabled: {9}{14}- CreateUser: {10}{14}- CreateDate: {11}{14}- UpdateUser: {12}{14}- UpdateDate: {13}{14}{16}", 
				this.Id,
				(this.Message == null) ? string.Empty : this.Message.ToString(),
				this.SmsType,
				this.SendTime,
				this.IsSendNow,
				this.IsSent,
				this.SendingTimes,
				(this.AppointmentId == null) ? string.Empty : this.AppointmentId.ToString(),
				(this.Note == null) ? string.Empty : this.Note.ToString(),
				this.IsDisabled,
				(this.CreateUser == null) ? string.Empty : this.CreateUser.ToString(),
				this.CreateDate,
				(this.UpdateUser == null) ? string.Empty : this.UpdateUser.ToString(),
				this.UpdateDate,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'Sms' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class SmsEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Sms"</remarks>
		public System.Int64 Id;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// Message : 
		/// </summary>
		public System.String		  Message = null;
		
		/// <summary>
		/// SmsType : Loại SMS: 1. SMS từ appointment, 2. SMS khác [do admin tự tạo]
		/// </summary>
		public System.Byte		  SmsType = (byte)0;
		
		/// <summary>
		/// SendTime : Thời gian gửi tin nhắn
		/// </summary>
		public System.DateTime		  SendTime = DateTime.MinValue;
		
		/// <summary>
		/// IsSendNow : Có gửi ngay hay không. Nếu không sẽ được gửi bằng windows service
		/// </summary>
		public System.Boolean		  IsSendNow = false;
		
		/// <summary>
		/// IsSent : Sms này đã được gửi chưa
		/// </summary>
		public System.Boolean		  IsSent = false;
		
		/// <summary>
		/// SendingTimes : Số lần SMS này được gửi. Vì có thể gửi lại
		/// </summary>
		public System.Int32		  SendingTimes = (int)0;
		
		/// <summary>
		/// AppointmentId : Id của appointment nếu đó là loại của appointment
		/// </summary>
		public System.String		  AppointmentId = null;
		
		/// <summary>
		/// Note : 
		/// </summary>
		public System.String		  Note = null;
		
		/// <summary>
		/// IsDisabled : 
		/// </summary>
		public System.Boolean		  IsDisabled = false;
		
		/// <summary>
		/// CreateUser : 
		/// </summary>
		public System.String		  CreateUser = null;
		
		/// <summary>
		/// CreateDate : 
		/// </summary>
		public System.DateTime		  CreateDate = DateTime.Now;
		
		/// <summary>
		/// UpdateUser : 
		/// </summary>
		public System.String		  UpdateUser = null;
		
		/// <summary>
		/// UpdateDate : 
		/// </summary>
		public System.DateTime		  UpdateDate = DateTime.Now;
		#endregion
			
		#region Source Foreign Key Property
				
		private Appointment _appointmentIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Appointment"/>.
		/// </summary>
		/// <value>The source Appointment for AppointmentId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Appointment AppointmentIdSource
      	{
            get { return this._appointmentIdSource; }
            set { this._appointmentIdSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#region SmsLogCollection
		
		private TList<SmsLog> _smsLogSmsId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _smsLogSmsId
		/// </summary>
		
		public TList<SmsLog> SmsLogCollection
		{
			get
			{
				if (_smsLogSmsId == null)
				{
				_smsLogSmsId = new TList<SmsLog>();
				}
	
				return _smsLogSmsId;
			}
			set { _smsLogSmsId = value; }
		}
		
		#endregion

		#region SmsReceiverCollection
		
		private TList<SmsReceiver> _smsReceiverSmsId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _smsReceiverSmsId
		/// </summary>
		
		public TList<SmsReceiver> SmsReceiverCollection
		{
			get
			{
				if (_smsReceiverSmsId == null)
				{
				_smsReceiverSmsId = new TList<SmsReceiver>();
				}
	
				return _smsReceiverSmsId;
			}
			set { _smsReceiverSmsId = value; }
		}
		
		#endregion

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			SmsEntityData _tmp = new SmsEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.Message = this.Message;
			_tmp.SmsType = this.SmsType;
			_tmp.SendTime = this.SendTime;
			_tmp.IsSendNow = this.IsSendNow;
			_tmp.IsSent = this.IsSent;
			_tmp.SendingTimes = this.SendingTimes;
			_tmp.AppointmentId = this.AppointmentId;
			_tmp.Note = this.Note;
			_tmp.IsDisabled = this.IsDisabled;
			_tmp.CreateUser = this.CreateUser;
			_tmp.CreateDate = this.CreateDate;
			_tmp.UpdateUser = this.UpdateUser;
			_tmp.UpdateDate = this.UpdateDate;
			
			#region Source Parent Composite Entities
			if (this.AppointmentIdSource != null)
				_tmp.AppointmentIdSource = MakeCopyOf(this.AppointmentIdSource) as Appointment;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._smsLogSmsId != null)
				_tmp.SmsLogCollection = (TList<SmsLog>) MakeCopyOf(this.SmsLogCollection); 
			if (this._smsReceiverSmsId != null)
				_tmp.SmsReceiverCollection = (TList<SmsReceiver>) MakeCopyOf(this.SmsReceiverCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			SmsEntityData _tmp = new SmsEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.Message = this.Message;
			_tmp.SmsType = this.SmsType;
			_tmp.SendTime = this.SendTime;
			_tmp.IsSendNow = this.IsSendNow;
			_tmp.IsSent = this.IsSent;
			_tmp.SendingTimes = this.SendingTimes;
			_tmp.AppointmentId = this.AppointmentId;
			_tmp.Note = this.Note;
			_tmp.IsDisabled = this.IsDisabled;
			_tmp.CreateUser = this.CreateUser;
			_tmp.CreateDate = this.CreateDate;
			_tmp.UpdateUser = this.UpdateUser;
			_tmp.UpdateDate = this.UpdateDate;
			
			#region Source Parent Composite Entities
			if (this.AppointmentIdSource != null && existingCopies.Contains(this.AppointmentIdSource))
				_tmp.AppointmentIdSource = existingCopies[this.AppointmentIdSource] as Appointment;
			else
				_tmp.AppointmentIdSource = MakeCopyOf(this.AppointmentIdSource, existingCopies) as Appointment;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.SmsLogCollection = (TList<SmsLog>) MakeCopyOf(this.SmsLogCollection, existingCopies); 
			_tmp.SmsReceiverCollection = (TList<SmsReceiver>) MakeCopyOf(this.SmsReceiverCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SmsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(SmsColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SmsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(SmsColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SmsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(SmsColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				SmsEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new SmsEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SmsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(SmsColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				SmsEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new SmsEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region SmsEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Sms"/> object.
	/// </remarks>
	public class SmsEventArgs : System.EventArgs
	{
		private SmsColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the SmsEventArgs class.
		///</summary>
		public SmsEventArgs(SmsColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the SmsEventArgs class.
		///</summary>
		public SmsEventArgs(SmsColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The SmsColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="SmsColumn" />
		public SmsColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Sms related events.
	///</summary>
	public delegate void SmsEventHandler(object sender, SmsEventArgs e);
	
	#region SmsComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class SmsComparer : System.Collections.Generic.IComparer<Sms>
	{
		SmsColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:SmsComparer"/> class.
        /// </summary>
		public SmsComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:SmsComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public SmsComparer(SmsColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="Sms"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="Sms"/> to compare.</param>
        /// <param name="b">The second <c>Sms</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Sms a, Sms b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Sms entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Sms a, Sms b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public SmsColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region SmsKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Sms"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class SmsKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the SmsKey class.
		/// </summary>
		public SmsKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the SmsKey class.
		/// </summary>
		public SmsKey(SmsBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the SmsKey class.
		/// </summary>
		public SmsKey(System.Int64 _id)
		{
			#region Init Properties

			this.Id = _id;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private SmsBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public SmsBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.Int64 _id;
		
		/// <summary>
		/// Gets or sets the Id property.
		/// </summary>
		public System.Int64 Id
		{
			get { return _id; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_id = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.Int64) EntityUtil.ChangeType(values["Id"], typeof(System.Int64)) : (long)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",
								Id,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region SmsColumn Enum
	
	/// <summary>
	/// Enumerate the Sms columns.
	/// </summary>
	[Serializable]
	public enum SmsColumn : int
	{
		/// <summary>
		/// Id : 
		/// </summary>
		[EnumTextValue("Id")]
		[ColumnEnum("Id", typeof(System.Int64), System.Data.DbType.Int64, true, true, false)]
		Id = 1,
		/// <summary>
		/// Message : 
		/// </summary>
		[EnumTextValue("Message")]
		[ColumnEnum("Message", typeof(System.String), System.Data.DbType.String, false, false, true, 256)]
		Message = 2,
		/// <summary>
		/// SmsType : Loại SMS: 1. SMS từ appointment, 2. SMS khác [do admin tự tạo]
		/// </summary>
		[EnumTextValue("SmsType")]
		[ColumnEnum("SmsType", typeof(System.Byte), System.Data.DbType.Byte, false, false, false)]
		SmsType = 3,
		/// <summary>
		/// SendTime : Thời gian gửi tin nhắn
		/// </summary>
		[EnumTextValue("SendTime")]
		[ColumnEnum("SendTime", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		SendTime = 4,
		/// <summary>
		/// IsSendNow : Có gửi ngay hay không. Nếu không sẽ được gửi bằng windows service
		/// </summary>
		[EnumTextValue("IsSendNow")]
		[ColumnEnum("IsSendNow", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, false)]
		IsSendNow = 5,
		/// <summary>
		/// IsSent : Sms này đã được gửi chưa
		/// </summary>
		[EnumTextValue("IsSent")]
		[ColumnEnum("IsSent", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, false)]
		IsSent = 6,
		/// <summary>
		/// SendingTimes : Số lần SMS này được gửi. Vì có thể gửi lại
		/// </summary>
		[EnumTextValue("SendingTimes")]
		[ColumnEnum("SendingTimes", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		SendingTimes = 7,
		/// <summary>
		/// AppointmentId : Id của appointment nếu đó là loại của appointment
		/// </summary>
		[EnumTextValue("AppointmentId")]
		[ColumnEnum("AppointmentId", typeof(System.String), System.Data.DbType.String, false, false, true, 20)]
		AppointmentId = 8,
		/// <summary>
		/// Note : 
		/// </summary>
		[EnumTextValue("Note")]
		[ColumnEnum("Note", typeof(System.String), System.Data.DbType.String, false, false, true, 1024)]
		Note = 9,
		/// <summary>
		/// IsDisabled : 
		/// </summary>
		[EnumTextValue("IsDisabled")]
		[ColumnEnum("IsDisabled", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, false)]
		IsDisabled = 10,
		/// <summary>
		/// CreateUser : 
		/// </summary>
		[EnumTextValue("CreateUser")]
		[ColumnEnum("CreateUser", typeof(System.String), System.Data.DbType.String, false, false, true, 200)]
		CreateUser = 11,
		/// <summary>
		/// CreateDate : 
		/// </summary>
		[EnumTextValue("CreateDate")]
		[ColumnEnum("CreateDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		CreateDate = 12,
		/// <summary>
		/// UpdateUser : 
		/// </summary>
		[EnumTextValue("UpdateUser")]
		[ColumnEnum("UpdateUser", typeof(System.String), System.Data.DbType.String, false, false, true, 200)]
		UpdateUser = 13,
		/// <summary>
		/// UpdateDate : 
		/// </summary>
		[EnumTextValue("UpdateDate")]
		[ColumnEnum("UpdateDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		UpdateDate = 14
	}//End enum

	#endregion SmsColumn Enum

} // end namespace
