//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppointmentBusiness.SmsBrand {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://w2m.bluezone.vn/", ConfigurationName="SmsBrand.SMSSoap")]
    public interface SMSSoap {
        
        // CODEGEN: Generating message contract since element name phone from namespace http://w2m.bluezone.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://w2m.bluezone.vn/SendSMSBrandName", ReplyAction="*")]
        AppointmentBusiness.SmsBrand.SendSMSBrandNameResponse SendSMSBrandName(AppointmentBusiness.SmsBrand.SendSMSBrandNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSBrandNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSBrandName", Namespace="http://w2m.bluezone.vn/", Order=0)]
        public AppointmentBusiness.SmsBrand.SendSMSBrandNameRequestBody Body;
        
        public SendSMSBrandNameRequest() {
        }
        
        public SendSMSBrandNameRequest(AppointmentBusiness.SmsBrand.SendSMSBrandNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://w2m.bluezone.vn/")]
    public partial class SendSMSBrandNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sms;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password;
        
        public SendSMSBrandNameRequestBody() {
        }
        
        public SendSMSBrandNameRequestBody(string phone, string sms, string sender, string username, string password) {
            this.phone = phone;
            this.sms = sms;
            this.sender = sender;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSBrandNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSBrandNameResponse", Namespace="http://w2m.bluezone.vn/", Order=0)]
        public AppointmentBusiness.SmsBrand.SendSMSBrandNameResponseBody Body;
        
        public SendSMSBrandNameResponse() {
        }
        
        public SendSMSBrandNameResponse(AppointmentBusiness.SmsBrand.SendSMSBrandNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://w2m.bluezone.vn/")]
    public partial class SendSMSBrandNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSBrandNameResult;
        
        public SendSMSBrandNameResponseBody() {
        }
        
        public SendSMSBrandNameResponseBody(string SendSMSBrandNameResult) {
            this.SendSMSBrandNameResult = SendSMSBrandNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSSoapChannel : AppointmentBusiness.SmsBrand.SMSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSSoapClient : System.ServiceModel.ClientBase<AppointmentBusiness.SmsBrand.SMSSoap>, AppointmentBusiness.SmsBrand.SMSSoap {
        
        public SMSSoapClient() {
        }
        
        public SMSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppointmentBusiness.SmsBrand.SendSMSBrandNameResponse AppointmentBusiness.SmsBrand.SMSSoap.SendSMSBrandName(AppointmentBusiness.SmsBrand.SendSMSBrandNameRequest request) {
            return base.Channel.SendSMSBrandName(request);
        }
        
        public string SendSMSBrandName(string phone, string sms, string sender, string username, string password) {
            AppointmentBusiness.SmsBrand.SendSMSBrandNameRequest inValue = new AppointmentBusiness.SmsBrand.SendSMSBrandNameRequest();
            inValue.Body = new AppointmentBusiness.SmsBrand.SendSMSBrandNameRequestBody();
            inValue.Body.phone = phone;
            inValue.Body.sms = sms;
            inValue.Body.sender = sender;
            inValue.Body.username = username;
            inValue.Body.password = password;
            AppointmentBusiness.SmsBrand.SendSMSBrandNameResponse retVal = ((AppointmentBusiness.SmsBrand.SMSSoap)(this)).SendSMSBrandName(inValue);
            return retVal.Body.SendSMSBrandNameResult;
        }
    }
}
