
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file DoctorFunc.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using ClinicDoctor.Entities.Validation;
#endregion

namespace ClinicDoctor.Entities
{
	///<summary>
	/// An object representation of the 'DoctorFunc' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class DoctorFuncBase : EntityBase, IDoctorFunc, IEntityId<DoctorFuncKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private DoctorFuncEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private DoctorFuncEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private DoctorFuncEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<DoctorFunc> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event DoctorFuncEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event DoctorFuncEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="DoctorFuncBase"/> instance.
		///</summary>
		public DoctorFuncBase()
		{
			this.entityData = new DoctorFuncEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="DoctorFuncBase"/> instance.
		///</summary>
		///<param name="_doctorUserName"></param>
		///<param name="_doctorShortName"></param>
		///<param name="_funcId"></param>
		///<param name="_funcTitle"></param>
		///<param name="_isDisabled"></param>
		///<param name="_createUser"></param>
		///<param name="_createDate"></param>
		///<param name="_updateUser"></param>
		///<param name="_updateDate"></param>
		public DoctorFuncBase(System.String _doctorUserName, System.String _doctorShortName, 
			System.Int64 _funcId, System.String _funcTitle, System.Boolean _isDisabled, System.String _createUser, 
			System.DateTime _createDate, System.String _updateUser, System.DateTime _updateDate)
		{
			this.entityData = new DoctorFuncEntityData();
			this.backupData = null;

			this.DoctorUserName = _doctorUserName;
			this.DoctorShortName = _doctorShortName;
			this.FuncId = _funcId;
			this.FuncTitle = _funcTitle;
			this.IsDisabled = _isDisabled;
			this.CreateUser = _createUser;
			this.CreateDate = _createDate;
			this.UpdateUser = _updateUser;
			this.UpdateDate = _updateDate;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="DoctorFunc"/> instance.
		///</summary>
		///<param name="_doctorUserName"></param>
		///<param name="_doctorShortName"></param>
		///<param name="_funcId"></param>
		///<param name="_funcTitle"></param>
		///<param name="_isDisabled"></param>
		///<param name="_createUser"></param>
		///<param name="_createDate"></param>
		///<param name="_updateUser"></param>
		///<param name="_updateDate"></param>
		public static DoctorFunc CreateDoctorFunc(System.String _doctorUserName, System.String _doctorShortName, 
			System.Int64 _funcId, System.String _funcTitle, System.Boolean _isDisabled, System.String _createUser, 
			System.DateTime _createDate, System.String _updateUser, System.DateTime _updateDate)
		{
			DoctorFunc newDoctorFunc = new DoctorFunc();
			newDoctorFunc.DoctorUserName = _doctorUserName;
			newDoctorFunc.DoctorShortName = _doctorShortName;
			newDoctorFunc.FuncId = _funcId;
			newDoctorFunc.FuncTitle = _funcTitle;
			newDoctorFunc.IsDisabled = _isDisabled;
			newDoctorFunc.CreateUser = _createUser;
			newDoctorFunc.CreateDate = _createDate;
			newDoctorFunc.UpdateUser = _updateUser;
			newDoctorFunc.UpdateDate = _updateDate;
			return newDoctorFunc;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int64 Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
					
				OnColumnChanging(DoctorFuncColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorFuncColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the DoctorUserName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 200)]
		public virtual System.String DoctorUserName
		{
			get
			{
				return this.entityData.DoctorUserName; 
			}
			
			set
			{
				if (this.entityData.DoctorUserName == value)
					return;
					
				OnColumnChanging(DoctorFuncColumn.DoctorUserName, this.entityData.DoctorUserName);
				this.entityData.DoctorUserName = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorFuncColumn.DoctorUserName, this.entityData.DoctorUserName);
				OnPropertyChanged("DoctorUserName");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the DoctorShortName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String DoctorShortName
		{
			get
			{
				return this.entityData.DoctorShortName; 
			}
			
			set
			{
				if (this.entityData.DoctorShortName == value)
					return;
					
				OnColumnChanging(DoctorFuncColumn.DoctorShortName, this.entityData.DoctorShortName);
				this.entityData.DoctorShortName = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorFuncColumn.DoctorShortName, this.entityData.DoctorShortName);
				OnPropertyChanged("DoctorShortName");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the FuncId property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int64 FuncId
		{
			get
			{
				return this.entityData.FuncId; 
			}
			
			set
			{
				if (this.entityData.FuncId == value)
					return;
					
				OnColumnChanging(DoctorFuncColumn.FuncId, this.entityData.FuncId);
				this.entityData.FuncId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorFuncColumn.FuncId, this.entityData.FuncId);
				OnPropertyChanged("FuncId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the FuncTitle property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 200)]
		public virtual System.String FuncTitle
		{
			get
			{
				return this.entityData.FuncTitle; 
			}
			
			set
			{
				if (this.entityData.FuncTitle == value)
					return;
					
				OnColumnChanging(DoctorFuncColumn.FuncTitle, this.entityData.FuncTitle);
				this.entityData.FuncTitle = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorFuncColumn.FuncTitle, this.entityData.FuncTitle);
				OnPropertyChanged("FuncTitle");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IsDisabled property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public override System.Boolean IsDisabled
		{
			get
			{
				return this.entityData.IsDisabled; 
			}
			
			set
			{
				if (this.entityData.IsDisabled == value)
					return;
					
				OnColumnChanging(DoctorFuncColumn.IsDisabled, this.entityData.IsDisabled);
				this.entityData.IsDisabled = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorFuncColumn.IsDisabled, this.entityData.IsDisabled);
				OnPropertyChanged("IsDisabled");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CreateUser property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 200)]
		public override System.String CreateUser
		{
			get
			{
				return this.entityData.CreateUser; 
			}
			
			set
			{
				if (this.entityData.CreateUser == value)
					return;
					
				OnColumnChanging(DoctorFuncColumn.CreateUser, this.entityData.CreateUser);
				this.entityData.CreateUser = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorFuncColumn.CreateUser, this.entityData.CreateUser);
				OnPropertyChanged("CreateUser");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CreateDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public override System.DateTime CreateDate
		{
			get
			{
				return this.entityData.CreateDate; 
			}
			
			set
			{
				if (this.entityData.CreateDate == value)
					return;
					
				OnColumnChanging(DoctorFuncColumn.CreateDate, this.entityData.CreateDate);
				this.entityData.CreateDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorFuncColumn.CreateDate, this.entityData.CreateDate);
				OnPropertyChanged("CreateDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the UpdateUser property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 200)]
		public override System.String UpdateUser
		{
			get
			{
				return this.entityData.UpdateUser; 
			}
			
			set
			{
				if (this.entityData.UpdateUser == value)
					return;
					
				OnColumnChanging(DoctorFuncColumn.UpdateUser, this.entityData.UpdateUser);
				this.entityData.UpdateUser = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorFuncColumn.UpdateUser, this.entityData.UpdateUser);
				OnPropertyChanged("UpdateUser");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the UpdateDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public override System.DateTime UpdateDate
		{
			get
			{
				return this.entityData.UpdateDate; 
			}
			
			set
			{
				if (this.entityData.UpdateDate == value)
					return;
					
				OnColumnChanging(DoctorFuncColumn.UpdateDate, this.entityData.UpdateDate);
				this.entityData.UpdateDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DoctorFuncColumn.UpdateDate, this.entityData.UpdateDate);
				OnPropertyChanged("UpdateDate");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Functionality"/>.
		/// </summary>
		/// <value>The source Functionality for FuncId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Functionality FuncIdSource
      	{
            get { return entityData.FuncIdSource; }
            set { entityData.FuncIdSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Staff"/>.
		/// </summary>
		/// <value>The source Staff for DoctorUserName.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Staff DoctorUserNameSource
      	{
            get { return entityData.DoctorUserNameSource; }
            set { entityData.DoctorUserNameSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("DoctorUserName", "Doctor User Name", 200));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("DoctorShortName", "Doctor Short Name", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("FuncTitle", "Func Title", 200));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("CreateUser", "Create User", 200));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("UpdateUser", "Update User", 200));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "DoctorFunc"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"Id", "DoctorUserName", "DoctorShortName", "FuncId", "FuncTitle", "IsDisabled", "CreateUser", "CreateDate", "UpdateUser", "UpdateDate"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as DoctorFuncEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (DoctorFunc) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<DoctorFunc>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as DoctorFunc);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed DoctorFunc Entity 
		///</summary>
		protected virtual DoctorFunc Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			DoctorFunc copy = new DoctorFunc();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Id = this.Id;
				copy.DoctorUserName = this.DoctorUserName;
				copy.DoctorShortName = this.DoctorShortName;
				copy.FuncId = this.FuncId;
				copy.FuncTitle = this.FuncTitle;
				copy.IsDisabled = this.IsDisabled;
				copy.CreateUser = this.CreateUser;
				copy.CreateDate = this.CreateDate;
				copy.UpdateUser = this.UpdateUser;
				copy.UpdateDate = this.UpdateDate;
			
			if (this.FuncIdSource != null && existingCopies.Contains(this.FuncIdSource))
				copy.FuncIdSource = existingCopies[this.FuncIdSource] as Functionality;
			else
				copy.FuncIdSource = MakeCopyOf(this.FuncIdSource, existingCopies) as Functionality;
			if (this.DoctorUserNameSource != null && existingCopies.Contains(this.DoctorUserNameSource))
				copy.DoctorUserNameSource = existingCopies[this.DoctorUserNameSource] as Staff;
			else
				copy.DoctorUserNameSource = MakeCopyOf(this.DoctorUserNameSource, existingCopies) as Staff;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed DoctorFunc Entity 
		///</summary>
		public virtual DoctorFunc Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed DoctorFunc Entity which is a deep copy of the current entity.
		///</summary>
		public virtual DoctorFunc DeepCopy()
		{
			return EntityHelper.Clone<DoctorFunc>(this as DoctorFunc);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as DoctorFuncEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new DoctorFuncEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as DoctorFuncEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(DoctorFuncColumn column)
		{
			switch(column)
			{
					case DoctorFuncColumn.Id:
					return entityData.Id != _originalData.Id;
					case DoctorFuncColumn.DoctorUserName:
					return entityData.DoctorUserName != _originalData.DoctorUserName;
					case DoctorFuncColumn.DoctorShortName:
					return entityData.DoctorShortName != _originalData.DoctorShortName;
					case DoctorFuncColumn.FuncId:
					return entityData.FuncId != _originalData.FuncId;
					case DoctorFuncColumn.FuncTitle:
					return entityData.FuncTitle != _originalData.FuncTitle;
					case DoctorFuncColumn.IsDisabled:
					return entityData.IsDisabled != _originalData.IsDisabled;
					case DoctorFuncColumn.CreateUser:
					return entityData.CreateUser != _originalData.CreateUser;
					case DoctorFuncColumn.CreateDate:
					return entityData.CreateDate != _originalData.CreateDate;
					case DoctorFuncColumn.UpdateUser:
					return entityData.UpdateUser != _originalData.UpdateUser;
					case DoctorFuncColumn.UpdateDate:
					return entityData.UpdateDate != _originalData.UpdateDate;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< DoctorFuncColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Id != _originalData.Id;
			result = result || entityData.DoctorUserName != _originalData.DoctorUserName;
			result = result || entityData.DoctorShortName != _originalData.DoctorShortName;
			result = result || entityData.FuncId != _originalData.FuncId;
			result = result || entityData.FuncTitle != _originalData.FuncTitle;
			result = result || entityData.IsDisabled != _originalData.IsDisabled;
			result = result || entityData.CreateUser != _originalData.CreateUser;
			result = result || entityData.CreateDate != _originalData.CreateDate;
			result = result || entityData.UpdateUser != _originalData.UpdateUser;
			result = result || entityData.UpdateDate != _originalData.UpdateDate;
			return result;
		}	
		
		///<summary>
		///  Returns a DoctorFunc Entity with the original data.
		///</summary>
		public DoctorFunc GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateDoctorFunc(
				_originalData.DoctorUserName,
				_originalData.DoctorShortName,
				_originalData.FuncId,
				_originalData.FuncTitle,
				_originalData.IsDisabled,
				_originalData.CreateUser,
				_originalData.CreateDate,
				_originalData.UpdateUser,
				_originalData.UpdateDate
				);
				
			return (DoctorFunc)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="DoctorFuncBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is DoctorFuncBase)
				return ValueEquals(this, (DoctorFuncBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="DoctorFuncBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Id.GetHashCode() ^ 
					((this.DoctorUserName == null) ? string.Empty : this.DoctorUserName.ToString()).GetHashCode() ^ 
					((this.DoctorShortName == null) ? string.Empty : this.DoctorShortName.ToString()).GetHashCode() ^ 
					this.FuncId.GetHashCode() ^ 
					((this.FuncTitle == null) ? string.Empty : this.FuncTitle.ToString()).GetHashCode() ^ 
					this.IsDisabled.GetHashCode() ^ 
					((this.CreateUser == null) ? string.Empty : this.CreateUser.ToString()).GetHashCode() ^ 
					this.CreateDate.GetHashCode() ^ 
					((this.UpdateUser == null) ? string.Empty : this.UpdateUser.ToString()).GetHashCode() ^ 
					this.UpdateDate.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="DoctorFuncBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(DoctorFuncBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="DoctorFuncBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="DoctorFuncBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="DoctorFuncBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(DoctorFuncBase Object1, DoctorFuncBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Id != Object2.Id)
				equal = false;
			if ( Object1.DoctorUserName != null && Object2.DoctorUserName != null )
			{
				if (Object1.DoctorUserName != Object2.DoctorUserName)
					equal = false;
			}
			else if (Object1.DoctorUserName == null ^ Object2.DoctorUserName == null )
			{
				equal = false;
			}
			if ( Object1.DoctorShortName != null && Object2.DoctorShortName != null )
			{
				if (Object1.DoctorShortName != Object2.DoctorShortName)
					equal = false;
			}
			else if (Object1.DoctorShortName == null ^ Object2.DoctorShortName == null )
			{
				equal = false;
			}
			if (Object1.FuncId != Object2.FuncId)
				equal = false;
			if ( Object1.FuncTitle != null && Object2.FuncTitle != null )
			{
				if (Object1.FuncTitle != Object2.FuncTitle)
					equal = false;
			}
			else if (Object1.FuncTitle == null ^ Object2.FuncTitle == null )
			{
				equal = false;
			}
			if (Object1.IsDisabled != Object2.IsDisabled)
				equal = false;
			if ( Object1.CreateUser != null && Object2.CreateUser != null )
			{
				if (Object1.CreateUser != Object2.CreateUser)
					equal = false;
			}
			else if (Object1.CreateUser == null ^ Object2.CreateUser == null )
			{
				equal = false;
			}
			if (Object1.CreateDate != Object2.CreateDate)
				equal = false;
			if ( Object1.UpdateUser != null && Object2.UpdateUser != null )
			{
				if (Object1.UpdateUser != Object2.UpdateUser)
					equal = false;
			}
			else if (Object1.UpdateUser == null ^ Object2.UpdateUser == null )
			{
				equal = false;
			}
			if (Object1.UpdateDate != Object2.UpdateDate)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((DoctorFuncBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static DoctorFuncComparer GetComparer()
        {
            return new DoctorFuncComparer();
        }
        */

        // Comparer delegates back to DoctorFunc
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(DoctorFunc rhs, DoctorFuncColumn which)
        {
            switch (which)
            {
            	
            	
            	case DoctorFuncColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            	
            	
            	case DoctorFuncColumn.DoctorUserName:
            		return this.DoctorUserName.CompareTo(rhs.DoctorUserName);
            		
            		                 
            	
            	
            	case DoctorFuncColumn.DoctorShortName:
            		return this.DoctorShortName.CompareTo(rhs.DoctorShortName);
            		
            		                 
            	
            	
            	case DoctorFuncColumn.FuncId:
            		return this.FuncId.CompareTo(rhs.FuncId);
            		
            		                 
            	
            	
            	case DoctorFuncColumn.FuncTitle:
            		return this.FuncTitle.CompareTo(rhs.FuncTitle);
            		
            		                 
            	
            	
            	case DoctorFuncColumn.IsDisabled:
            		return this.IsDisabled.CompareTo(rhs.IsDisabled);
            		
            		                 
            	
            	
            	case DoctorFuncColumn.CreateUser:
            		return this.CreateUser.CompareTo(rhs.CreateUser);
            		
            		                 
            	
            	
            	case DoctorFuncColumn.CreateDate:
            		return this.CreateDate.CompareTo(rhs.CreateDate);
            		
            		                 
            	
            	
            	case DoctorFuncColumn.UpdateUser:
            		return this.UpdateUser.CompareTo(rhs.UpdateUser);
            		
            		                 
            	
            	
            	case DoctorFuncColumn.UpdateDate:
            		return this.UpdateDate.CompareTo(rhs.UpdateDate);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<DoctorFuncKey> Members
		
		// member variable for the EntityId property
		private DoctorFuncKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual DoctorFuncKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new DoctorFuncKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("DoctorFunc")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{11}{10}- Id: {0}{10}- DoctorUserName: {1}{10}- DoctorShortName: {2}{10}- FuncId: {3}{10}- FuncTitle: {4}{10}- IsDisabled: {5}{10}- CreateUser: {6}{10}- CreateDate: {7}{10}- UpdateUser: {8}{10}- UpdateDate: {9}{10}{12}", 
				this.Id,
				(this.DoctorUserName == null) ? string.Empty : this.DoctorUserName.ToString(),
				(this.DoctorShortName == null) ? string.Empty : this.DoctorShortName.ToString(),
				this.FuncId,
				(this.FuncTitle == null) ? string.Empty : this.FuncTitle.ToString(),
				this.IsDisabled,
				(this.CreateUser == null) ? string.Empty : this.CreateUser.ToString(),
				this.CreateDate,
				(this.UpdateUser == null) ? string.Empty : this.UpdateUser.ToString(),
				this.UpdateDate,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'DoctorFunc' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class DoctorFuncEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "DoctorFunc"</remarks>
		public System.Int64 Id;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// DoctorUserName : 
		/// </summary>
		public System.String		  DoctorUserName = null;
		
		/// <summary>
		/// DoctorShortName : 
		/// </summary>
		public System.String		  DoctorShortName = null;
		
		/// <summary>
		/// FuncId : 
		/// </summary>
		public System.Int64		  FuncId = (long)0;
		
		/// <summary>
		/// FuncTitle : 
		/// </summary>
		public System.String		  FuncTitle = null;
		
		/// <summary>
		/// IsDisabled : 
		/// </summary>
		public System.Boolean		  IsDisabled = false;
		
		/// <summary>
		/// CreateUser : 
		/// </summary>
		public System.String		  CreateUser = null;
		
		/// <summary>
		/// CreateDate : 
		/// </summary>
		public System.DateTime		  CreateDate = DateTime.Now;
		
		/// <summary>
		/// UpdateUser : 
		/// </summary>
		public System.String		  UpdateUser = null;
		
		/// <summary>
		/// UpdateDate : 
		/// </summary>
		public System.DateTime		  UpdateDate = DateTime.Now;
		#endregion
			
		#region Source Foreign Key Property
				
		private Functionality _funcIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Functionality"/>.
		/// </summary>
		/// <value>The source Functionality for FuncId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Functionality FuncIdSource
      	{
            get { return this._funcIdSource; }
            set { this._funcIdSource = value; }
      	}
		private Staff _doctorUserNameSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Staff"/>.
		/// </summary>
		/// <value>The source Staff for DoctorUserName.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Staff DoctorUserNameSource
      	{
            get { return this._doctorUserNameSource; }
            set { this._doctorUserNameSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			DoctorFuncEntityData _tmp = new DoctorFuncEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.DoctorUserName = this.DoctorUserName;
			_tmp.DoctorShortName = this.DoctorShortName;
			_tmp.FuncId = this.FuncId;
			_tmp.FuncTitle = this.FuncTitle;
			_tmp.IsDisabled = this.IsDisabled;
			_tmp.CreateUser = this.CreateUser;
			_tmp.CreateDate = this.CreateDate;
			_tmp.UpdateUser = this.UpdateUser;
			_tmp.UpdateDate = this.UpdateDate;
			
			#region Source Parent Composite Entities
			if (this.FuncIdSource != null)
				_tmp.FuncIdSource = MakeCopyOf(this.FuncIdSource) as Functionality;
			if (this.DoctorUserNameSource != null)
				_tmp.DoctorUserNameSource = MakeCopyOf(this.DoctorUserNameSource) as Staff;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			DoctorFuncEntityData _tmp = new DoctorFuncEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.DoctorUserName = this.DoctorUserName;
			_tmp.DoctorShortName = this.DoctorShortName;
			_tmp.FuncId = this.FuncId;
			_tmp.FuncTitle = this.FuncTitle;
			_tmp.IsDisabled = this.IsDisabled;
			_tmp.CreateUser = this.CreateUser;
			_tmp.CreateDate = this.CreateDate;
			_tmp.UpdateUser = this.UpdateUser;
			_tmp.UpdateDate = this.UpdateDate;
			
			#region Source Parent Composite Entities
			if (this.FuncIdSource != null && existingCopies.Contains(this.FuncIdSource))
				_tmp.FuncIdSource = existingCopies[this.FuncIdSource] as Functionality;
			else
				_tmp.FuncIdSource = MakeCopyOf(this.FuncIdSource, existingCopies) as Functionality;
			if (this.DoctorUserNameSource != null && existingCopies.Contains(this.DoctorUserNameSource))
				_tmp.DoctorUserNameSource = existingCopies[this.DoctorUserNameSource] as Staff;
			else
				_tmp.DoctorUserNameSource = MakeCopyOf(this.DoctorUserNameSource, existingCopies) as Staff;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DoctorFuncColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(DoctorFuncColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DoctorFuncColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(DoctorFuncColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DoctorFuncColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(DoctorFuncColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				DoctorFuncEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new DoctorFuncEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DoctorFuncColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(DoctorFuncColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				DoctorFuncEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new DoctorFuncEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region DoctorFuncEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="DoctorFunc"/> object.
	/// </remarks>
	public class DoctorFuncEventArgs : System.EventArgs
	{
		private DoctorFuncColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the DoctorFuncEventArgs class.
		///</summary>
		public DoctorFuncEventArgs(DoctorFuncColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the DoctorFuncEventArgs class.
		///</summary>
		public DoctorFuncEventArgs(DoctorFuncColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The DoctorFuncColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="DoctorFuncColumn" />
		public DoctorFuncColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all DoctorFunc related events.
	///</summary>
	public delegate void DoctorFuncEventHandler(object sender, DoctorFuncEventArgs e);
	
	#region DoctorFuncComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class DoctorFuncComparer : System.Collections.Generic.IComparer<DoctorFunc>
	{
		DoctorFuncColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:DoctorFuncComparer"/> class.
        /// </summary>
		public DoctorFuncComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:DoctorFuncComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public DoctorFuncComparer(DoctorFuncColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="DoctorFunc"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="DoctorFunc"/> to compare.</param>
        /// <param name="b">The second <c>DoctorFunc</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(DoctorFunc a, DoctorFunc b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(DoctorFunc entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(DoctorFunc a, DoctorFunc b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public DoctorFuncColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region DoctorFuncKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="DoctorFunc"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class DoctorFuncKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the DoctorFuncKey class.
		/// </summary>
		public DoctorFuncKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the DoctorFuncKey class.
		/// </summary>
		public DoctorFuncKey(DoctorFuncBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the DoctorFuncKey class.
		/// </summary>
		public DoctorFuncKey(System.Int64 _id)
		{
			#region Init Properties

			this.Id = _id;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private DoctorFuncBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public DoctorFuncBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.Int64 _id;
		
		/// <summary>
		/// Gets or sets the Id property.
		/// </summary>
		public System.Int64 Id
		{
			get { return _id; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_id = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.Int64) EntityUtil.ChangeType(values["Id"], typeof(System.Int64)) : (long)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",
								Id,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region DoctorFuncColumn Enum
	
	/// <summary>
	/// Enumerate the DoctorFunc columns.
	/// </summary>
	[Serializable]
	public enum DoctorFuncColumn : int
	{
		/// <summary>
		/// Id : 
		/// </summary>
		[EnumTextValue("Id")]
		[ColumnEnum("Id", typeof(System.Int64), System.Data.DbType.Int64, true, true, false)]
		Id = 1,
		/// <summary>
		/// DoctorUserName : 
		/// </summary>
		[EnumTextValue("DoctorUserName")]
		[ColumnEnum("DoctorUserName", typeof(System.String), System.Data.DbType.String, false, false, true, 200)]
		DoctorUserName = 2,
		/// <summary>
		/// DoctorShortName : 
		/// </summary>
		[EnumTextValue("DoctorShortName")]
		[ColumnEnum("DoctorShortName", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		DoctorShortName = 3,
		/// <summary>
		/// FuncId : 
		/// </summary>
		[EnumTextValue("FuncId")]
		[ColumnEnum("FuncId", typeof(System.Int64), System.Data.DbType.Int64, false, false, false)]
		FuncId = 4,
		/// <summary>
		/// FuncTitle : 
		/// </summary>
		[EnumTextValue("FuncTitle")]
		[ColumnEnum("FuncTitle", typeof(System.String), System.Data.DbType.String, false, false, true, 200)]
		FuncTitle = 5,
		/// <summary>
		/// IsDisabled : 
		/// </summary>
		[EnumTextValue("IsDisabled")]
		[ColumnEnum("IsDisabled", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, false)]
		IsDisabled = 6,
		/// <summary>
		/// CreateUser : 
		/// </summary>
		[EnumTextValue("CreateUser")]
		[ColumnEnum("CreateUser", typeof(System.String), System.Data.DbType.String, false, false, true, 200)]
		CreateUser = 7,
		/// <summary>
		/// CreateDate : 
		/// </summary>
		[EnumTextValue("CreateDate")]
		[ColumnEnum("CreateDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		CreateDate = 8,
		/// <summary>
		/// UpdateUser : 
		/// </summary>
		[EnumTextValue("UpdateUser")]
		[ColumnEnum("UpdateUser", typeof(System.String), System.Data.DbType.String, false, false, true, 200)]
		UpdateUser = 9,
		/// <summary>
		/// UpdateDate : 
		/// </summary>
		[EnumTextValue("UpdateDate")]
		[ColumnEnum("UpdateDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		UpdateDate = 10
	}//End enum

	#endregion DoctorFuncColumn Enum

} // end namespace
